# Generated by Django 6.1.1 on 2026-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_id', models.CharField(help_text='Molecule ID from ANPDB', max_length=100, unique=True)),
                ('smiles', models.TextField(help_text='SMILES string representation')),
                ('molecular_weight', models.FloatField()),
                ('log_p', models.FloatField(help_text='Lipophilicity')),
                ('tpsa', models.FloatField(help_text='Polarity / Total Polar Surface Area')),
                ('h_bond_donors', models.IntegerField()),
                ('h_bond_acceptors', models.IntegerField()),
                ('rotatable_bonds', models.IntegerField()),
                ('ring_count', models.IntegerField()),
                ('fingerprint', models.TextField(help_text='Bit string representation of Morgan FP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
